// Regenerate the self-contained demo data files:
//   wasm-demo-b64.js  – the wasm-gc artifact as base64 (loads over file://)
//   samples.js        – small fixtures inlined so the page works diskless
// Usage: node embed.mjs <wasm> [fixtures-dir]
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmPath = process.argv[2];
const fixturesDir = process.argv[3] ?? join(here, "..", "..", "tests", "fixtures");
if (!wasmPath) {
  console.error("usage: node embed.mjs <wasm> [fixtures-dir]");
  process.exit(2);
}

const wasm = await readFile(wasmPath);
await writeFile(
  join(here, "wasm-demo-b64.js"),
  `window.MNPY_WASM_B64 = "${wasm.toString("base64")}";\n`,
);
console.log(`wasm-demo-b64.js: ${wasm.length} bytes -> ${Math.ceil((wasm.length * 4) / 3)} base64 chars`);

const samples = [
  ["f4_2x3_c_le_v1.npy", "float32 · 2x3 · little-endian"],
  ["c8_2x3_c_le_v1.npy", "complex64 · 2x3 · little-endian"],
  ["i2_2x2x2_c_le_v1.npy", "int16 · 2x2x2 · 3-dim"],
  ["i4_2x3_f_be_v1.npy", "int32 · 2x3 · big-endian · Fortran order"],
  ["f8_scalar_c_le_v1.npy", "float64 · scalar (0-dim)"],
];
const entries = [];
for (const [file, label] of samples) {
  const bytes = await readFile(join(fixturesDir, file));
  entries.push({ file, label, b64: bytes.toString("base64") });
}
const lines = [
  "// Generated by embed.mjs – small .npy fixtures inlined for the demo page.",
  "window.MNPY_SAMPLES = [",
  ...entries.map(
    (e) =>
      `  { file: ${JSON.stringify(e.file)}, label: ${JSON.stringify(e.label)}, b64: ${JSON.stringify(e.b64)} },`,
  ),
  "];",
  "",
];
await writeFile(join(here, "samples.js"), lines.join("\n"));
console.log(`samples.js: ${entries.length} fixtures embedded`);
